### ISSUE TITLE
Link to schema builder in README is dead

### ISSUE THREAD

**Issue by daviddelon** [ikkez/f3-cortex#1]
Hello, 
In the README, the link to schema builder is dead,  https://github.com/ikkez/F3-Sugar/tree/master-v3/SchemaBuilder should be replaced by https://github.com/ikkez/f3-schema-builder .

**Comment by ikkez** [comment]
Hi. Thanks for the info. I'm currently reviewing and extending the docs. It'll be fixed when I am done,.. hopefully soon :)

**Comment by ikkez** [comment]
fixed in the readme update
