### ISSUE TITLE
Documentation Cast could be improved clarify and or

### ISSUE THREAD

**Issue by atbu** [ikkez/f3-cortex#10]

**Comment by atbu** [comment]
Not really an issue  … This might be a bit picky but I stumbled several times about it.
under point Additional Data Types
you clarified with a comment that mentioned lines are "either or"

    'type' => self::DT_JSON
    // or
    'type' => 'JSON'


which makes clear what is meant.

Under "cast" you express something similar.

    $user->cast(NULL, array(
    '*' => 0      // cast all own relations to the given depth, 
                // 0 doesn't cast any relation (default if this key is missing)
      'modelA' => 0 // if a relation key is defined here, modelA is being loaded and casted,
                    // but not its own relations, because the depth is 0 for it
      'modelB' => 1 // modelB and all its 1st level relations are loaded and casted
      'modelC' => array(...) // you can recursively extend this cast array scheme
    ));

When I first read it I thought it´s an example and copied & pasted it which resulted in an error. This could be easily solved by adding a colon after each row.

**Comment by ikkez** [comment]
yes it's just a sample, but I added the colons now for clarification.
