### ISSUE TITLE
Surround fields using function

### ISSUE THREAD

**Issue by kumy** [ikkez/f3-cortex#102]
I was wondering how [`pgcrypto`](https://www.postgresql.org/docs/current/pgcrypto.html) may be implemented in `f3`/`cortex` environment. My goal is to cipher some "sensitive" data such as email addresses.

Example usage from https://blog.andreiavram.ro/encrypt-postgresql-column/
```sql
CREATE TABLE public.users (
id serial primary key,
email varchar not null unique
);
 
INSERT INTO users (email) values
(pgp_sym_encrypt('adoe@domain.tld', 'longsecretencryptionkey')),
(pgp_sym_encrypt('bdoe@domain.tld', 'longsecretencryptionkey'));

SELECT pgp_sym_decrypt(email::bytea, 'longsecretencryptionkey') FROM users;
```

As we can see, we need to surround `email` field in `SELECT`, `UPDATE` queries.

I think we can use [`virtual fields`](https://github.com/ikkez/f3-cortex#virtual-fields) to retrieve the data. It should give something like (but untested):
```php
$user = new User();
$user->_email = 'pgp_sym_decrypt(email::bytea, ?)';
$user->load('id = ?', ['longsecretencryptionkey', 1]);
echo $user->_email;
…
## I wonder if the two parameters will be detected as in #99
```

However I have no idea how we can do the `INSERT` statement.

@ikkez do you think it is feasible with current `cortex` implementation?

**Comment by ikkez** [comment]
Cortex doesnt care of this.. it's the underlaying F3 SQL mapper that would do it, and currently is not able to do so. Nevertheless, maybe you can just create a DB Trigger update the field values on insert.

**Comment by kumy** [comment]
> just create a DB Trigger to update the field values on insert.

hum, how the trigger will be aware of the "longsecretencryptionkey"? It would be a bad implementation if we have it stored in the database (inside the function trigger code).

**Comment by ikkez** [comment]
Well in that case, why use an pgsql-based encryption function anyways? There are dozens of other options available that would let you implement encryption in php directly

**Comment by kumy** [comment]
Having to manage cryptographic implementations in multiple app that access the same database is not as efficient as having it implemented natively in database. :)

**Comment by ikkez** [comment]
Yeah okay, understand.. that's true.. sorry but I think than the only option I see right now is with a TRIGGER (you can set your crypto key as temp variable with an sql query before, I think) or you use a custom db->exec INSERT query to call that function.

**Comment by kumy** [comment]
I'll go for the [custom queries](https://github.com/ikkez/f3-cortex/issues/102#issuecomment-616505597).

Thanks for your support.
