### ISSUE TITLE
Possible to order by a relation

### ISSUE THREAD

**Issue by adkurz** [ikkez/f3-cortex#104]
Hello,

I'm trying to order a result set (cortex collection)by the column of a relation.
Example,
I have 2 tables, contracts and contractors.
The contract table has a contractor_id (1-n-relation, one contract has one contractor (belongs-to-one))
Now, I try to order the contracts table by the name of the contractor, something like 'order' => 'contractor_id.name', but it doesn't work. I'm using the order option in the find-method, but the orderBy-method of cortex collections doesn't work too.
Is it possible to order by the column of a relation?

**Comment by ikkez** [comment]
Hi.
Well we could think that when the query contains a join with a table, it should be easy to order by that field. Basically that's correct, but depending on the relation type and the used internal strategy, it's not always the case like that. So I probably cannot just add this and make it work easily for all cases. 
What does work however, would be to use a different "aggregation point"... meaning, you could just query by the contractor in the desired order and fetch all related contracts afterwards.. something like this:

```php
$contracts=[];
$contractors = $contactor->find(NULL, ['order'=>'name ASC']);
if ($contractors) {
  $contracts = $contractors->getAll('contract');
}
```

In case you need to add conditions to the contract query as well, you can do so with `has` and `filter` methods before calling `find`.

**Comment by adkurz** [comment]
Thank you for this possibility, but it isn't working with my setup. I try to use the specific order in the paginate-method of Cortex/F3-SQL-Mapper.

**Comment by ikkez** [comment]
I understand.. well I did a little test and probably found da workaround. See this:

```php
$contracts = new Contracts();
$contracts->has('contractor_id', ['id > 0']); // you need any has filter to force a table join
$res = $contracts->paginate(0,10,null, ['order'=>'contractorts__contractor_id.name ASC']);
```

Do you use any `has` filter yet? Because in order make it work, you'll need one with any filter in it at the momemt. You can then order by the joined table alias name with is name in the scheme {table_name}__{model_field}. 
Try my sample above.. if that's not working, add a has filter and check the generated SQL query with $db->log() to see whats shown in the query.

If that does work for you, I can have a look to make it more convenient in the order option, even if no has filter was applied.
thanks

**Comment by adkurz** [comment]
Hello,

Thank you very much, it works perfectly. A more convenient method without a has filter would be very great.

**Comment by ikkez** [comment]
I've added something. try this:

```php
$contracts = new Contracts();
$res = $contracts->paginate(0,10,null, ['order'=>'@contractor_id.name ASC']);
```

Usage is: `@` sign with the relation field name + the related field.. like `@field.field`. The `@field` is then automatically replaced with the correct table alias value.

**Comment by adkurz** [comment]
Hello,

The new version doesn't work following sql-statement is produced
SELECT (COUNT(*)) as _rows FROM `auftrag` LEFT JOIN `objekt` AS `objekt__objekt_id` ON `auftrag`.`objekt_id` = `objekt__objekt_id`.`id` WHERE
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 [D:\xampp\htdocs\btam\lib\bcosca\fatfree-core\db\sql.php:226]
DB\Cortex->count([],['order'=>'@objekt_id.bezeichnung DESC'],0)

**Comment by ikkez** [comment]
well first, it doesnt make any sense to add ordering to a count query, and second, please use NULL instead of [] for empty filter conditions.

**Comment by adkurz** [comment]
Sorry, i used [] instead null for the filter, this solved the problem.
I didn't used a count query, it seems to be a query triggered by the paginate method.
Thank you, now it works great.
