### ISSUE TITLE
$primary class property doesn't work

### ISSUE THREAD

**Issue by adkurz** [ikkez/f3-cortex#106]
Hello,
I have to use an older pgsql database with cortex. Therefore, I have to change the primary key for the users table.
So i write in the Class \Model\User:
class user extends Base {
...
protected $primary = 'user_id';
...
}
Then, I try to load a specific user:
$user->load(['_id = ?', $userId]);
But following error is shown:
SQLSTATE[42703]: Undefined column: 7 Error: Column »id« doesn't exist
Row 1: ...password","usergroup" FROM "user" WHERE "id" IS N... ^ ...
Made I a mistake or is this a bug?
System: Cortex 1.7, PHP 7.4FPM, Debian 10, Apache2, latest F3, pgSQL
Thanks.

**Comment by ikkez** [comment]
That should actually work like this. Have you any relations set up and used a hard coded `id` somewhere? I'm just wondering where this `WHERE "id" IS N´ comes from... is that a `"id" IS NULL` condition?

**Comment by adkurz** [comment]
No, there aren't any relations yet. In the log, 
Not all queries are wrong, some work, other not.
Now the specific code (some names in german (old database)
Wrong query:
Code:
$user = new \Model\User();
$user->load(['_id = ?', $userId]);
Result: 
SELECT "benutzerid","nachname","vorname","benutzername","passwort","benutzergruppe" FROM "benutzer" WHERE "id" = 508
In model class:
$primary = 'benutzerid';
'benutzerid' is not in fieldconf.
So, in the select, the right column (benutzerid) is used, but in the where part, cortex uses 'id' instead of 'benutzerid'.

**Comment by ikkez** [comment]
should be fixed in the latest commit
