### ISSUE TITLE
sql db

### ISSUE THREAD

**Issue by stvowi** [ikkez/f3-cortex#11]
1. Ich finde es sinnvoll, wenn man bei SQL DB's die Methode exec, begin, roolback, commit direkt aufrufen könnte. (Short Cut Methoden: http://fatfreeframework.com/sql#begin,rollback&commit)

Eine Methode zum Aufruf von Stored Procedures (z.B. von MySQL) wäre auch sehr hilfreich.

2 Relations

Warum kann man nicht den Datentyp für das Foreign Key -Feld (belongs-to-* Felder in fieldConf -Array ) angeben?

3. Datentypen

Was passiert, wenn in einer bestehenden SQL DB die Datentypen nich genau der vordefinierten Typen z.B. VARCHAR256 entsprechen?

**Comment by ikkez** [comment]
Nabend.
1. Nutze doch dafür bitte einfach das DB Objekt direkt, welches sowieso an den Mapper übergeben wurde. Falls du dieses public machen möchtest, erweitere deine Model Klasse und füge eine getter Methode für die DB hinzu.
2. nicht nötig. wird automatisch aus dem gegenüberliegenden Schema ausgelesen
3. macht nichts. das ist nur interessant falls du die setup() Methode nutzen möchtest, um Tabellen automatisch zu generieren. Den Rest liest der F3 Mapper direkt aus dem Tabellenschema.

**Comment by stvowi** [comment]
Wie wärs...
/** @var Cursor */
	protected $mapper;

wenn man "public $mapper;" setzt? oder mit einer getMapper-Methode?
Dann kommt man an alle Mapper-Methoden ran.
