### ISSUE TITLE
Force TTL expiration

### ISSUE THREAD

**Issue by sbraaa** [ikkez/f3-cortex#111]
Hi,
Suppose I usually load some data that don't change very often so I want to put them in cache "forever".
The first time I'll made some CRUd operations on that data I'll need to invalidate existing cache or rather made ttl of that data expire.
Is that possible using f3-cortex? Does it makes it automatically?

**Comment by ikkez** [comment]
Hi... well it doesn't do it automatically, but you there's a way to do it. 
You can either use the result set and the Cache class directly to decide if you want to reload the data or not of cause and write a little helper. Or you use the rather undocumented feature of cache tags in F3, see https://github.com/bcosca/fatfree-core/pull/166

Basically you turn $ttl to an array, use a very long ttl and give it a certain tag for that action. If you decide to invalidate the cache your use cache->clear with that certain tag to only wipe the things you need.

**Comment by sbraaa** [comment]
Ok, thanks! 
your approach is clear (and is the same I usually use to manage cache in memcached)! 
Thank you!
