### ISSUE TITLE
PHP 5.4 compat

### ISSUE THREAD

**Issue by ekhaled** [ikkez/f3-cortex#112]
Hi,
We use fatfree-core with this.
fatfree-core has [PHP 5.4 compat](https://github.com/bcosca/fatfree-core/blob/master/composer.json#L7)

If [this line](https://github.com/ikkez/f3-cortex/blob/master/lib/db/cortex.php#L728) could be modified, Cortex works in PHP 5.4 too

Is this acceptable? if so, I can do a quick PR

**Comment by ikkez** [comment]
sure. We can change that.

**Comment by ekhaled** [comment]
Any chance this can be merged and released?
