### ISSUE TITLE
has-many relation produce error 500

### ISSUE THREAD

**Issue by le51** [ikkez/f3-cortex#114]
Hello,

thank you for your library, it's pretty cool but I'm facing an issue:
```php

// in Categorie model this result in an error 500
        'posts' => array(
            'has-many' => array('\Model\Post', 'category_id'),
        )
// while in post model it's ok
        'category_id' => array(
            'type' => 'TINYINT',
            'belongs-to' => '\Model\Categorie',
        ),

```
Internal Server Error
PDO: near "FROM": syntax error

[devel/f3/api/vendor/bcosca/fatfree-core/base.php:2347] Base->error()
[devel/f3/api/vendor/bcosca/fatfree-core/db/sql.php:268] user_error()
[devel/f3/api/vendor/bcosca/fatfree-core/db/sql/mapper.php:310] DB\SQL->exec()
[devel/f3/api/vendor/bcosca/fatfree-core/db/sql/mapper.php:347] DB\SQL\Mapper->select()
[devel/f3/api/vendor/ikkez/f3-cortex/lib/db/cortex.php:917] DB\SQL\Mapper->find()
[devel/f3/api/vendor/ikkez/f3-cortex/lib/db/cortex.php:633] DB\Cortex->filteredFind()
[devel/f3/api/vendor/ikkez/f3-cortex/lib/db/cortex.php:1866] DB\Cortex->find()
[devel/f3/api/vendor/bcosca/fatfree-core/magic.php:86] DB\Cortex->get()
[devel/f3/api/vendor/bcosca/fatfree-core/magic.php:127] Magic->offsetget()
[devel/f3/api/app/lib/controller/jsonapi.php:751] Magic->__get()
[devel/f3/api/app/lib/controller/jsonapi.php:645] Controller\JsonApi->oneToArray()
[devel/f3/api/app/lib/controller/jsonapi.php:122] Controller\JsonApi->manyToJson()
[devel/f3/api/vendor/bcosca/fatfree-core/base.php:1960] Controller\JsonApi->getList()
[devel/f3/api/vendor/bcosca/fatfree-core/base.php:1759] Base->call()
[devel/f3/api/public/index.php:6] Base->run()

it looks like something went wrong in the the query building phase. but I can't investigate further.

**Comment by ikkez** [comment]
Check you config... `belongs-to` does not exist.. you probably meant `belongs-to-one` ;)

**Comment by le51** [comment]
Hi, thank you for the quick reply :-)

... yes, the belongs-to (!= belongs-to-one) was malformed. It's okay now, so you can close the issue, 
... and sorry for the noise ;-)  

Cheers
