### ISSUE TITLE
Potential code error: Use of unassigned variable '$cond'

### ISSUE THREAD

**Issue by kumy** [ikkez/f3-cortex#121]
My editor  just pointed me to this `Use of unassigned variable '$cond'`:

https://github.com/ikkez/f3-cortex/blob/2896a9b052cf30284f52b08c72313a7c9b302ca8/lib/db/cortex.php#L1094

It was introduced by this [commit](https://github.com/ikkez/f3-cortex/commit/2ef6d810ac0a6a52d69fc87baa2071861e97df32)

I'm personally not impacted by this, but it's worth reporting :shrug:

**Comment by ikkez** [comment]
fixed. thanks for reporting
