### ISSUE TITLE
Bind value for IN operator must be a populated array

### ISSUE THREAD

**Issue by teamayu** [ikkez/f3-cortex#127]
Hi Christian.

Can you tell me why this doesn't work with Cortex? It does with using the standard f3 model.

`$model->find(['baseprice > ? and sgroups not in(?) and status = ?', 0,'carts',1],['order' => 'name ASC'])`

I have also tried:

`$model->find(['baseprice > ? and sgroups not in(?) and status = ?', 0,['carts'],1],['order' => 'name ASC'])`

This also usually works, but not in Cortex:

`$model->find(['baseprice > ? and sgroups not in(?) and status = ?', [0,'carts',1]],['order' => 'name ASC'])`

**Comment by ikkez** [comment]
Try it with 

`not in ?`

and than give it an array in the params. It's perhaps a little glitch the in regex pattern.

**Comment by teamayu** [comment]
Thanks, it still doesn't work.

`$model->find(['baseprice > ? and sgroups not in ? and status = ?', 0,['carts'],1],['order' => 'name ASC'])`

This gives an error saying the params counts don't match. No probs though, I just removed not in and replace it with the comparison operator.

`$model->find(['baseprice > ? and sgroups != ? and status = ?', 0,'carts',1],['order' => 'name ASC'])`

Appreciate the help.

**Comment by ikkez** [comment]
The basic syntax for using the IN operator is 

```php
$model->find(['column_A IN ? and column_b NOT IN ?', [1, 2, 3], ['a', 'b', 'c']);
```

The error `Bind value for IN operator must be a populated array` could mean that you are passing an array which is empty, so check if there's actually a value in it.

I'll close this issue. Feel free to reopen if the problem persists
