### ISSUE TITLE
Column relation (belongs-to-one) problem

### ISSUE THREAD

**Issue by exodus4d** [ikkez/f3-cortex#13]
I ran into a very strange behavior while setting up my models... It took me quiet a while until i have pinned down the problem. 
I don´t know if this is a bug, but want to share what i figured out. 

The order in your `$fieldConf` array is very important! If you have relational information for a colum, the type for that relation e.g. `belongs-to-one` has to be in the **first** place. This will not work:

``` php
class UserModel extends BasicModel {
    protected $table = 'user';
    protected $fieldConf = [
        'apis' => [
            'has-many' => ['Model\UserApiModel', 'userId']
        ],

class UserApiModel extends BasicModel {
    protected $table = 'user_api';
    protected $fieldConf = [
        'userId' => [
            'type' => Schema::DT_INT,
            'index' => true,
            'belongs-to-one' => 'Model\UserModel'
        ],
```

I don´t get any results for `$userModel->apis`, even if there is data available.

##### Problem

Cortex tries to access the related $fieldConf from `UserApiModel ` in [L1517](https://github.com/ikkez/f3-cortex/blob/master/lib/db/cortex.php#L1517). This works correctly. In the next Line the `$relType = key($relFieldConf[$fromConf[1]]);` gets the first array key as relationalType. This is in my case *"type"* instead of *"belongs-to-one"*.

##### Solution

Move the relationalType at the first array index in your `$fieldConf` like this:

``` php
class UserApiModel extends BasicModel {
    protected $table = 'user_api';
    protected $fieldConf = [
        'userId' => 
            'belongs-to-one' => 'Model\UserModel'
            'type' => Schema::DT_INT,
            'index' => true,
        ],
```

Feel free to close this issue, if this is intended or already known.

**Comment by ikkez** [comment]
Nice catch! No of course this was not intented. It should be fixed now.

**Comment by exodus4d** [comment]
Thanks for the quick fix. It works ;)
