### ISSUE TITLE
Q: Many-to-many relation

### ISSUE THREAD

**Issue by webbird** [ikkez/f3-cortex#14]
I feel a bit dumb, but I can't get relations to work for me. I have a very simple setup:

Table 'blocks', pkey field 'block_id', second column 'type'
Table 'data', pkey field 'data_id'

In the Block model:

        $fieldConf = array(
            'block_id' => array(
                'has-many' => array('\Crissando\Model\Data','data_id'),
            ),
        );

In the Data model:

        $fieldConf = array(
            'data_id' => array(
                'has-many' => array('\Crissando\Model\Block','block_id'),
            ),
        );

Using the ::setup() method created the pivot table. Next I use:

        $einblock  = new \Crissando\Model\Block();
        $daten     = $einblock->load(array('block_id=?',1));

I would expect to get the data of the related 'data' table, but I only get the data of the 'blocks' table.

    Array
    (
        [block_id] => 
        [type] => 1
    )

What do I miss here?

Edit: I used `$daten->cast(NULL,2)` to get the result.

**Comment by ikkez** [comment]
Hi. Well basically it looks correctly so far. What did you mean with *pkey*. Is it really your primary key? I expect you have those fields in your tables:

block table:
* id (primary key, autoincrement)
* type

data table:
* id (primary key, autoincrement)
* anyText

Now you create "virtual fields" that are mapped to the related model:

block model:
```
$fieldConf = array(
        'blocks' => array(
            'has-many' => array('\Crissando\Model\Data','data'),
        ),
    );
```

data model:
```
  $fieldConf = array(
        'data' => array(
            'has-many' => array('\Crissando\Model\Block','blocks'),
        ),
    );
```

Now you should get you nested data.

If you primary key is other than `id`, you need to [tell the model](https://github.com/ikkez/f3-cortex#primary). I.e.:

```php
namespace Model;
class Block extends \DB\Cortex {
  protected
    $fieldConf = array(
        'blocks' => array(
            'has-many' => array('\Crissando\Model\Data','data'),
        ),
    ),
    $db = 'DB',
    $table = 'blocks',   
    $primary = 'block_id';
}
```

**has-many** is always a virtual field. Never name this field configuration like an existing table column.

**Comment by webbird** [comment]
Thank you for your elaborate answer. Works perfectly now. I would have bet I tried this variant, but obviously I didn't. ;)
Thanks again for your help and this very helpful extension!
