### ISSUE TITLE
Q: Retrieve only specific columns

### ISSUE THREAD

**Issue by blindpenguin** [ikkez/f3-cortex#17]
Hi there,

in classical SQL i can select specific columns i want to know. Something like:

`select username, email from users;`

Maybe i'm blind, but i didn't find the relevant part in the documentation. Or i just don't understand it. So how exactly can i get those columns?

My current implementation using the paginate function:

`$thing = $collection->paginate(0, $limit, null, [
                'order' => 'username, company asc',
            ]);`

Ignore that "$collection". I just changed everything from Mongo to MySQL.

**Comment by ikkez** [comment]
Sure. Check the [fields](https://github.com/ikkez/f3-cortex#fields) method. It should work like this:
```php
$mapper->fields(['username','email']); // this will set a whitelist of allowed fields
$results = $mapper->paginate(0, $limit, null, [ 'order' => 'username, company asc']);
```
The resulting SQL will only select username and email from your table.

**Comment by blindpenguin** [comment]
Well, something's going wrong on my side. :D

`$collection->fields(['username', 'email']);

  $thing = $collection->paginate(0, $limit, null, [
        'order' => 'username, company asc',
  ]);`

var_dump shows me this:

`SELECT `id`,`username`,`password`,`email`,`group`,`company`,`active`,`verified`,`activationcode` FROM `members` ORDER BY `username`, company asc LIMIT 10`

**Comment by ikkez** [comment]
Sorry, I cannot reproduce this. It's working as expected here. Which versions do you use? Try to update F3, because basically this field limitation is being used from the underlying F3 SQL mapper.

**Comment by blindpenguin** [comment]
It's already up to date. 3.5.1, fetched with composer.

That's basically the affected code:
http://pastebin.com/jAG88hD8

Maybe i did something wrong. If i var_dump the $collection->fields stuff, then it gives me the full table, not only the stuff i told it to load. I also deleted the cache, just to be sure.

**Comment by ikkez** [comment]
Hm, I'm not sure what's wrong on your side. But it's working here. Here is a little demo for you:

**composer.json**
```json
{
    "name": "ikkez/test",
    "require": {
        "bcosca/fatfree": "^3.5",
        "ikkez/f3-cortex": "^1.4"
    },
    "authors": [
        {
            "name": "ikkez",
            "email": "ikkez0n3@gmail.com"
        }
    ]
}
```
run `composer install`.
add `index.php`: http://pastebin.com/Xx6dngBV
make sure this folder is writable.
call the script in the browser returns (at least to me):

```
Array
(
    [0] => Array
        (
            [username] => ikkez
            [password] => secret
            [email] => mail@domain.com
            [group] => 1
            [company] => ACME Inc.
            [active] => 1
            [verified] => 1
            [activationcode] => 1asxt110plnza
            [_id] => 1
        )

)
Array
(
    [0] => Array
        (
            [username] => ikkez
            [email] => mail@domain.com
            [_id] => 1
        )

)
```

SQL Log contains: 
```
Thu, 11 Feb 2016 11:34:17 +0100 (0.2ms) SELECT "id","username","password","email","group","company","active","verified","activationcode" FROM "members" ORDER BY "name" desc LIMIT 10
```
and
```
Thu, 11 Feb 2016 11:34:17 +0100 (0.2ms) SELECT "id","username","email" FROM "members" ORDER BY "name" desc LIMIT 10
```

So you see... it should work.

**Comment by blindpenguin** [comment]
I think now i get it. There has to be a model, right? I thought this would be optional.

**Comment by ikkez** [comment]
Oh it is optional. It was just for the sake of that example. You can do the same thing with this:

```php
$member = new \DB\Cortex($f3->get('DB'),'members');
$member->fields(array('username','email'));
$results = $member->paginate(0,10,null,array('order'=>'name desc'));
```
