### ISSUE TITLE
Soft Deleting

### ISSUE THREAD

**Issue by Deprime** [ikkez/f3-cortex#20]
Hi! I'm realy like F3-Cortex. I would like to suggest a small improvement - Soft deleting.
A great example of this functionality can be seen in the [Eloquent library in Laravel framework](https://laravel.com/docs/5.1/eloquent#soft-deleting).

I would be very grateful if this feature appeared in the F3-Cortex.

**Comment by ekhaled** [comment]
you can use the `beforeerase()` method to achieve this. example:

```php
class User extends \DB\Cortex{
     public function __construct(){

           $this->beforeerase(function ($instance) {

                 if (isset($instance->fieldConf['deleted'])) {
                      $instance->deleted = 1;
                      $instance->save();
                      return false;
                }

                return true;
           });
    }

}
```

this assumes you have a field called `deleted` in your DB table

**Comment by ikkez** [comment]
closed, as using beforeerase is the way to go
