### ISSUE TITLE
fields: exclude a relational field will exclude all the relational element

### ISSUE THREAD

**Issue by cracrayol** [ikkez/f3-cortex#23]
The commit made on 2015-12-29 (https://github.com/ikkez/f3-cortex/commit/7f95462e7b8ce74a73ae1725dce8ccb34bb4c4b5) automatically add missing relation fields when using whitelist.

But if blacklist is used ($exclude set to true), blacklisting a relation field fieldA.fieldB will exclude all fieldA and return nothing for this relation.

A quick (and dirty?) fix : $fields[] = $key; ---> if(!$exclude) $fields[] = $key; (l. 176)

**Comment by ikkez** [comment]
Sorry for the delay. It was slightly more complex ;-)
