### ISSUE TITLE
How does the relation work? I got Error.

### ISSUE THREAD

**Issue by Kekesed** [ikkez/f3-cortex#26]
![1461596196169screensave](https://cloud.githubusercontent.com/assets/12927266/14788099/a6274c4a-0b30-11e6-8e88-21ce42ae6f8d.png)

I'm trying to cast the object as i loaded them.
the error was
```
500 Internal Server Error
PDOStatement: Table 'kambeng.users__groupid_mm___' doesn't exist
```

My UserModel:
``` php
<?php
Namespace Model;
Class UserModel extends \DB\Cortex{
  protected
   $db = null,
   $table='users',
   $fluid = true,
   $primary = 'id',
   $fieldConf = array(
    "id" => array(
      "type" => \DB\SQL\Schema::DT_INT,
    ),
    "groupId" => array(
      //"type" => \DB\SQL\Schema::DT_INT,
      "has-one"=> array('\Model\GroupModel', 'id'), //-> this causes the problem.
    ),
    "name" => array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128,
    ),
    "email" => array(
      "type" => \DB\SQL\Schema::DT_VARCHAR256,
    ),
    "password" => array(
      "type" => \DB\SQL\Schema::DT_TEXT,
    ),
    "ppid"=> array(
      "type"=>\DB\SQL\Schema::DT_INT,
      //"has-one"=> array('\Model\ImageModel', 'pid') -> This causes error too, same as groupid
    ),
    "nama_depan" => array(
      'type'=> \DB\SQL\Schema::DT_TEXT
    ),
    "nama_belakang" => array(
      'type'=> \DB\SQL\Schema::DT_TEXT
    ),
    "tgl_lahir" => array(
      'type'=> \DB\SQL\Schema::DT_DATE
    ),
    "name" => array(
      'type'=> \DB\SQL\Schema::DT_TEXT
    ),
    "regdate" => array(
      'type'=> \DB\SQL\Schema::DT_DATETIME
    ),
    "bio" => array(
      'type'=> \DB\SQL\Schema::DT_TEXT
    ),
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
}
```

and then, why my primary key `id` didn't show up? it shows `_id` when i tried to cast it without any relation defined in the model.
Thanks.

**Comment by ikkez** [comment]
It looks like it could not find the foreign table definition for the GroupModel Model. Is that set up?

* it is not necessary to set up the primary key, if it does not differ from the name `id` and type `int`. drop it.
* the primary key is transformed into `_id` for legacy reasons and for better support in the different F3 mappers. You could turn this off with `CORTEX.standardiseID`, though I do not recommend.
*  the groupId `has-one` link looks wrong. Either you meant `belongs-to-one` here, or it should probably be `array('\Model\GroupModel', 'user')`.
* your query does not utilized prepared statements.. use `$user->load(array('name = ?','admin'));` instead, otherwise it could cause errors.

**Comment by Kekesed** [comment]
- What's the different `has-one` and `belongs-to-one` in this case? I'm thinking that the User `has-one` Groupid `belongs-to-one` User. Is it wrong? hhehehe 
- i did! when i set it into fluid mode, the `parent::__construct()` raises error `The table ActivationKey is exist` (i added more column to the UserModel).

Thanks!

**Comment by ikkez** [comment]
No it's not wrong.. it's exactly how you have described it. But your setting seems twisted. The belongs-to-* field is the actual field that is created in the table, and holds the id of the foreign model. This is the `id` field by default. The has-* field is the counterpart that should point to the opposite relation field (belongs-to-*). To make it more clear, just add the fields to your statement:
> The field User.group has-one Group model and the field Group.user belongs-to-one User (`User.id`).

**Comment by Kekesed** [comment]
![1461654541137screensave](https://cloud.githubusercontent.com/assets/12927266/14809642/9910c648-0bb8-11e6-8299-ad765290037c.png)

UserModel.php
```php
Namespace Model;
Class UserModel extends \DB\Cortex{
  protected
   $db = null,
   $table='users',
   $fluid = false,
   $primary = 'id',
   $fieldConf = array(
    "id" => array(
      "type" => \DB\SQL\Schema::DT_INT,
    ),
    "groupId" => array(
      "has-one"=> array('\Model\GroupModel', 'groupid'),
    ),
    "email" => array(
      "type" => \DB\SQL\Schema::DT_VARCHAR256,
      "nullable"=>false,
    ),
  (...)
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
```

GroupModel.php
```php
Namespace Model;
Class GroupModel extends \DB\Cortex{
  protected
   $db = null,
   $table='groups',
   $fluid = false,      // triggers the SQL Fluid Mode, default: false
   $primary = 'id',   // name of the primary key (auto-created), default: id
   $fieldConf = array(
    "id" => array(
      "belongs-to-one"=>'\Model\UserModel'
    ),
    "name"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128
    )
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
}
```

nope, that didn't resolve my issue :cry: :cry:

**Comment by Kekesed** [comment]
hmm... thanks! *taking bunch notes*

**Comment by Kekesed** [comment]
one more, is it possible to set the coalition for `DT_TEXT` and `DT_VARCHAR`? I want to save chinese words, so, i need to set it into `utf8` thing...

**Comment by Kekesed** [comment]
next, should we set the both model's field to make a relation?

for example, i want to make a connection to image database, this is the model:
```php
Namespace Model;
Class ImageModel extends \DB\Cortex {
  protected
   $db = null,
   $table='tblimage',
   $primary = 'pid',   // name of the primary key (auto-created), default: id
   $fieldConf = array(
    "pid"=>array(
      "belongs-to-one"=> '\Model\UserModel'
    ),
    "uid"=>array(
      "belongs-to-one"=> '\Model\UserModel'
    ),
    "link"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128,
    ),
    "source"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128,
    ),
    "link"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128,
    ),
    "aksesable"=>array(
      "type" => \DB\SQL\Schema::DT_BOOL,
    ),
    "size"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128,
    ),
    "date_added"=>array(
      "type" => \DB\SQL\Schema::DT_DATETIME,
    ),
    "srcx"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128,
    ),
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
}
```

But the problem is, this image is used to whole project, like post tumbhnails, and more. If the `tblimage.pid` need to specify that it connect to user as `users.ppid` then how make it 'portable' to other post? like, i don't want to specify the model that it connects to other table too...

thanks again, i'm very noob at this :sad:

**Comment by ikkez** [comment]
Well, have you read the docs carefully? You have to stop thinking in tables.. you are working with models. it makes no sense to put a relation onto a primary key.. in the point of view for the mapper, it always tries to resolve that relation and the other mapper when anything accesses that key.. which makes it pretty impossible to work with its id for loading/saving actions.
If an image belongs to a user.. set it up like this. i.e. image.user -> belongs-to-one -> user.profile_image
and user.profile_image -> has-one -> image.user
has-* fields are virtual, and belongs-to* are actual tables columns.. so 
ImageModel, `'user' =>array('belongs-to-one' => '\Models\UserModel')`.. that's the shortcut for `array('belongs-to-one' => array('\Models\UserModel','id'))`.
in UserModel, `'profile_image' => array('has-one'=>array('\Models\ImageModel','user'))`... which basically tells the model, to have a look into the table of the image model and the field `user`, because it contains the user ids (foreign keys) that it needs to build the relation the inverse way.

**Comment by ikkez** [comment]
of course you can also setup multiple relations to a single image, so you can reuse it with other models too.. but when you say the you need it for a post thumbnail as well, I would guess that the post is made by a user.. so just connect the post and the user and you can get the image by accessing `post.user.profile_image`. done.

**Comment by Kekesed** [comment]
just thinking more case:
if user uploaded new profile picture, then the picture is saved to the database, then should i worrying the `image.user` to set it to `0`? So the model wont get confused if there's more than 1 row `image.user` setted to same value?

**Comment by ikkez** [comment]
well you should care about deleting the other rows before adding the new. or, if you need the old images, keep them in the database, make it a has-many relation, and add a filter that returns only the last sorted by creation date or something like that..

**Comment by Kekesed** [comment]
hmm... i have problem with `has-many` relation, it raises error `array_key_exists() expects parameter 2 to be array, null given` on `cortex.php line 157`.

ACLModel.php
```php
Namespace Model;
Class ACLModel extends \DB\Cortex{
  protected
   $db = null,
   $table='acl',
   $fluid = true,      // triggers the SQL Fluid Mode, default: false
   $primary = 'id',   // name of the primary key (auto-created), default: id
   $ttl = 120,         // caching time of field schema, default: 60
   $rel_ttl = 30,
   $fieldConf = array(
    "id" => array(
      "type" => \DB\SQL\Schema::DT_INT,
    ),
    "action"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128
    ),
    "groupid"=>array(
      "belongs-to-one"=>'\Model\GroupModel'
    ),
    "rule"=>array(
      "type" => \DB\SQL\Schema::DT_INT
    )
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
}
```

GroupIdModel.php
```php
Namespace Model;
Class GroupModel extends \DB\Cortex{
  protected
   $db = null,
   $table='groups',
   $fluid = false,      // triggers the SQL Fluid Mode, default: false
   $primary = 'id',   // name of the primary key (auto-created), default: id
   $fieldConf = array(
    "name"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128
    ),
    "allowed_to"=>array(
      'has-many'=>array('\Model\ACLModel', 'groupId')
    )
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
}
```

what should i give attention when having the `has-many` relation?

**Comment by Kekesed** [comment]
i fixed it!

```php
Namespace Model;
Class GroupModel extends \DB\Cortex{
  protected
   $db = null,
   $table='groups',
   $fluid = false,      // triggers the SQL Fluid Mode, default: false
   $primary = 'id',   // name of the primary key (auto-created), default: id
   $fieldConf = array(
    "name"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128
    ),
    "allowed_to"=>array(
      'has-many'=>array('\Model\ACLModel', 'groupid')
    )
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
}
```

```php
<?php
Namespace Model;
Class ACLModel extends \DB\Cortex{
  protected
   $db = null,
   $table='acl',
   $fieldConf = array(
    "action"=>array(
      "type" => \DB\SQL\Schema::DT_VARCHAR128
    ),
    "groupid"=>array(
      "belongs-to-one"=>'\Model\GroupModel'
    ),
    "rule"=>array(
      "type" => \DB\SQL\Schema::DT_INT
    )
  );
  function __construct() {
     $this->db = \kksd\Sesi::$DB;
     parent::__construct();
  }
}
```

still hard to know the `has-many` relation.

how to make statement of it?
```php
   "allowed_to"=>array(
      'has-many'=>array('\Model\ACLModel', 'groupid')
    )
```
> `groups.allowed_to` has-many `acl`s with `acl.groupid` are same with `groups.id`?.


this is the `has-many` relationship on user on acl table:
```php
   "allowed_to"=> array(
      "has-many"=>array('\Model\ACLModel', 'groupid')
    ),
```

> `users.allowed_to` has-many `acl`s with `acl.groupid` are same with `users.(what)`?

**Comment by ikkez** [comment]
Sorry, but it's up to you how you design your ACL models.. i cannot guess what your intention is, or how it should work. I would say a user can have a group and a group and a user can have settings.. both has to be linked together somehow and at the end one would probably need a function to merge the settings together, but I don't know... ACL can be complex... i recommend you make yourself a diagram first.. if you have problems linking models together, you're welcome... but I think I have not understand yet what you're trying to do.

**Comment by Kekesed** [comment]
yup,okay.
thanks for the explanation howto use it.
