### ISSUE TITLE
Before Find and Before Load

### ISSUE THREAD

**Issue by acemureithi** [ikkez/f3-cortex#27]
Hey I would request before find and before load events.
Supposing I have 30 models eg users, cars etc and then organisation and each must be in an organisation (apart from organisation), and to avoid writing
```php
$user->find(array('organisation = ?', $f3->get('SESSION.organisation'));  
$car->find(array('organisation = ?', $f3->get('SESSION.organisation'));  
//etc
```
is there a work around.

**Comment by ikkez** [comment]
yeah, use the opposite model. that should make it easier:
```php
$organisation->load(array('id = ?',$f3->get('SESSION.organisation')));
//$organisation->users
//$organisation->cars
// etc.
```

**Comment by acemureithi** [comment]
Thanks, though decided to use traits and mergeFilter
