### ISSUE TITLE
MySQL keywords INTERVAL and DAY in filter condition => extra backticks

### ISSUE THREAD

**Issue by xvester** [ikkez/f3-cortex#28]
Hello!

I have a table with datetime field "fealta" (MySQL). This filter condition:

```
$prod = new \Models\Producto;
$prods = $prod->find(['fealta <= NOW() - INTERVAL 1 DAY']);
```

fails and triggers this error (note extra backticks surrounding DAY):

    PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1 `DAY`' at line 1

Using only SQL Mapper works and does not trigger error:

```
$prod2 = new \DB\SQL\Mapper($f3->get('DB'), 'productos');
$prods = $prod2->find(['fealta <= NOW() - INTERVAL 1 DAY']);

```

It could be something related to Cortex's function sql_quoteCondition. If I replace (line 2237, cortex.php version 1.4.2-dev):

`if (preg_match('/\b(AND|OR|IN|LIKE|NOT)\b/i',$match[2]))`

with

`if (preg_match('/\b(AND|OR|IN|LIKE|NOT|DAY|INTERVAL)\b/i',$match[2]))`

then it doesn't trigger that error anymore.

**Comment by ikkez** [comment]
Hi.
Well the quotation of fields is necessary, but it was build to skip functions, exactly for this purpose [[1](https://github.com/ikkez/f3-cortex/blob/master/lib/db/cortex.php#L2230-L2233)]. In your case, it should help if you just wrap it into a DATE function or use the mysql function for date substraction:
 
```php
$prods = $prod2->find(['fealta <= DATE(NOW() - INTERVAL 1 DAY)']);
// or
$prods = $prod2->find(['fealta <= DATE_SUB(NOW(), INTERVAL 1 DAY)']);
```

**Comment by ikkez** [comment]
Were you able to solve the problem?

**Comment by xvester** [comment]
Hi! By using the SQL syntax you suggested, it works now.
Thanks.
