### ISSUE TITLE
Problem with has-many

### ISSUE THREAD

**Issue by joshms123** [ikkez/f3-cortex#29]
Hello,
When using the 'has-many' relation in a field configuration, the model defined cannot be loaded; it tries to load the first letter of the model, which of course does not exist. When examining the code, even though the key has already been selected, it then goes on to select array[0], being the first letter of the model.

**Comment by ikkez** [comment]
That's because it expects the field configuration for `has-*` relations to be an array. It should be
`'has-many' => array('\Namespace\ClassName','foreignKey')`

**Comment by joshms123** [comment]
Hello,
Yes, that makes sense now. Sorry about that. Error on my part. Thanks for the pointer.
