### ISSUE TITLE
Erase to return bool

### ISSUE THREAD

**Issue by acemureithi** [ikkez/f3-cortex#3]
````php
public function erase($filter = null)
	{
		$filter = $this->queryParser->prepareFilter($filter, $this->dbsType);
		if (!$filter && $this->emit('beforeerase')!==false) {
			if ($this->fieldConf) {
				foreach($this->fieldConf as $field => $conf)
					if (isset($conf['has-many']) &&
						$conf['has-many']['hasRel']=='has-many')
						$this->set($field,null);
				$this->save();
			}
			$this->mapper->erase();
			$this->emit('aftererase');
		} elseif($filter)
			$this->mapper->erase($filter);
	}
````
Suppose I have a condition that a category cannot be delete if any book is belongs to him.
So I set a beforeerase callback.
Now I want to do something like this: But there is no return for erase
```php
function delete($f3, $params){
        $category = new \Admin\Models\Category();

        $category
            ->load(array('id = ?',$params['id']));
        try{
            if($category->erase())
            \Flash::instance()->addMessage("Record #".$params['id']." Deleted",'info');
        }
        catch (\Exception $e){
            \Flash::instance()->addMessage($e->getMessage(),'error');
        }
        $f3->reroute('/' . $f3->get('PARAMS.app'). '/categories/index');
    }

**Comment by ikkez** [comment]
Hi. No there is no return in `erase()` but you can throw an exception in your beforeerase event or set a var in the F3 hive, or use the F3->error function, and only add the "recorded deleted info" when no error occured.

**Comment by acemureithi** [comment]
Sorry to ask this, what is the implication of adding one?

**Comment by ikkez** [comment]
You mean a return statement based on the event trigger? mh, well yeah I think that would be possible.

**Comment by acemureithi** [comment]
Look at the cursor documentation
````php
    /**
	*	Delete current record
	*	@return int|bool
	**/
	function erase() {
		$this->query=array_slice($this->query,0,$this->ptr,TRUE)+
			array_slice($this->query,$this->ptr,NULL,TRUE);
		$this->skip(0);
	}
````
But there is no return ??  
Does it boil down to the cursor having no return?

**Comment by ikkez** [comment]
The cursor only cares about the cursor. Each of the mapper implementations extend that erase method differently. jig returns a bool, sql the number of affected rows and mongo always true. since that isn't useful anyhow, cortex->erase doesn't have a return yet. I can add one dependent on the beforeerase event, if that is what you hade in mind?

**Comment by acemureithi** [comment]
Could you give an example of how the dependent would work?

**Comment by ikkez** [comment]
See latest commit. That should fix it.
