### ISSUE TITLE
Mapping existing relationship?

### ISSUE THREAD

**Issue by TonyRyan** [ikkez/f3-cortex#30]
Hi, I'm working with some legacy data and trying to figure out how to accomplish the relationship mapping.

`Users` table has `role` column (not `role_id` as you would expect) with an integer that corresponds to the `UserRoles` table PK `id` field. There's also another field `name` on the `UserRoles` table that I'm trying to access.

I would like to access this in code something along the lines of 
```php 
$user->role->name;
``` 
Currently 
```php 
$user->role;
``` 
just gives me the id (does not bring in the UserRole mapping).

```php
class User extends \DB\Cortex
{
  protected
		$fieldconf = array(
      'role' => array(
        'belongs-to-one' => '\Model\UserRole'
      )
		),
		$table = "Users",
		$db = "db";
}
```

```php
class UserRole extends \DB\Cortex
{
  protected
    $fieldconf = array(
      'users' => array(
        'has-many' => array('\Model\User', 'role')
      )
    ),
		$table = "UserRoles",
		$db = "db";
}
```

I'm guessing it's trying to find the 'role_id' column instead of just 'role'. Is that the problem? Can that be overridden somehow?

Thanks for any info.

**Comment by ikkez** [comment]
Hi Tony... well the configuration looks correct. It's no problem that the column name is `role`. There are no vague expectations in the code that would need a `role_id` column name for this case. It should work the way you have built it now.

Can you maybe just test the other way round, like:

```php
$userRoles = new \Model\UserRoles();
$all_user_roles = $userRoles->find();
$users = $all_user_roles->getAll('users');
print_r($users[0]->cast());
```

**Comment by TonyRyan** [comment]
Okay, so I'm thoroughly confused now. I'm not entirely sure what I changed but it's working now.

But, not as I expected.

```php
$user->role;
```
Now contains the string "admin" which is the correct role, but that comes from the `UserRoles`.`role_name` column. So, I would expect to access it like:

```php
$user->role->role_name;
```
The `role_name` column isn't mentioned anywhere in my code. So how did Cortex decide to use that for the $user->role; value?

**Comment by TonyRyan** [comment]
Unfortunately, that gives me
```
Fatal error: Call to a member function cast() on null
````

**Comment by ikkez** [comment]
I think I've found the issue. Can you please try to rename your field configuration array var name?!
`$fieldconf` should be `$fieldConf`

**Comment by TonyRyan** [comment]
Whoops, nice catch! That was indeed the issue. Thanks for spotting it :+1:
