### ISSUE TITLE
Sort has-many relation

### ISSUE THREAD

**Issue by TonyRyan** [ikkez/f3-cortex#31]
Is there any way to sort the collection generated by a has-many relation by a field in the foreign table (not the foreign key)? Say an Author 'has-many' Posts. I get them via ```$author->posts``` can those posts be sorted by Post.Date or can I iterate them in an order sorted by Post.Date?

Thanks for any help!

**Comment by ikkez** [comment]
Yes this should be possible by setting a filter:
```php
$author = new \Model\Author();
// add filter
$author->filter('posts',null,array('order'=>'date DESC'));
// find multiple
$results = $author->find();
// or load just one
$author->load();
```

each `$author->posts` should be sorted now.

**Comment by TonyRyan** [comment]
Thanks! I didn't realize the $options array worked like that with filter()
