### ISSUE TITLE
Saving with relation may have error?

### ISSUE THREAD

**Issue by xmory** [ikkez/f3-cortex#33]
User class

``` php
// \models\User class
'role' => array(
         'belongs-to-one' => '\models\Role'
      ),
```

Role class

``` php
// \models\Role class
'users' => array(
          'has-many' => array('\models\User','role')
           ),
```

Then

``` php
     $user = new \models\User();
     //some codes for $user
     $role_admin = new \models\Role();
     //some codes for $role_admin
    $role_admin->save();             //call this first
    $user->role =$role_admin ; 
    $role_admin->users = array($user);
    $user->save();                       //call this second
```

Everything is right.

But if this

``` php
     $user = new \models\User();
     //some codes for $user
     $role_admin = new \models\Role();
     //some codes for $role_admin
    $user->role =$role_admin ; 
    $role_admin->users = array($user);
    $user->save();                       //call this first
    $role_admin->save();             //call this second
```

Error comes in the last line with description: "PDOStatement: Unknown column 'Array' in 'field list'"
It failed in this code:

``` php
DB\SQL\Mapper->select('`id`,`name`,(Array) AS `users`',array('id=?',1),array('group'=>NULL,'order'=>NULL,'limit'=>0,'offset'=>0),0)
```

Is this a bug?

**Comment by ikkez** [comment]
this happens in the sql mapper, when you try to set a value to a fields that was not found in the table schema. this could be due to an old cache entry (maybe clear it) or because of misconfiguration or a typo.
You setup looks good, maybe there's a bug, but I'm wondering why you try to save both sides.. it's somehow redundant.. 

```php
$user = new \models\User();
//some codes for $user
$role_admin = new \models\Role();
//some codes for $role_admin
$role_admin->save();
$user->role =$role_admin ; 
$user->save();
```
this should be enough. After you reload $role_admin, your new user should already appear in `$role_admin->users`.

**Comment by xmory** [comment]
Yes,it's right. I used to think these two codes are both right, no matter saving $role before or after.

**Comment by ikkez** [comment]
It currently only matters because of the auto increment id that would be missing to bind the relation correctly. I could add an auto-save mechanism in `save()` for this, but it would implicitly call the save hooks. Not sure if this is always "safe" to do, or if it might lead to misbehaviour.
