### ISSUE TITLE
[Bug] before/afterupdate event is fired on ->erase() call

### ISSUE THREAD

**Issue by exodus4d** [ikkez/f3-cortex#34]
When I delete an object: `$object->erase();` there is an `afterupdate` event fired as well. This is triggered by an `$object->save();` (in case there are relations that should be deleted as well):  https://github.com/ikkez/f3-cortex/blob/master/lib/db/cortex.php#L1088

**Comment by exodus4d** [comment]
I have added a small check if object has changed in `ease()` function. This fixes the problem for me:

``` php
	public function erase($filter = null)
	{
		$filter = $this->queryParser->prepareFilter($filter, $this->dbsType);
		if (!$filter) {
			if ($this->emit('beforeerase')===false)
				return false;
			if ($this->fieldConf) {
			    $changed = false;
				foreach($this->fieldConf as $field => $conf){
                    if (isset($conf['has-many']) && $conf['has-many']['hasRel']=='has-many'){
                        $this->set($field,null);
                        $changed = true;
                    }
                }
                if($changed){
                    $this->save();
                }
			}
			$this->mapper->erase();
			$this->emit('aftererase');
		} elseif($filter)
			$this->mapper->erase($filter);
		return true;
	}
```

**Comment by stvowi** [comment]
...there will be also fired onload & beforesave...it's not good by erease

**Comment by exodus4d** [comment]
Agree. Maybe we could add a new parameter to `save()`function . e.g. "skipCallbacks" to prevent calling thise functions for relational objects. But to be honest I can´t predict any side-effects or unwanted behavior. So it was just a workaround for myselfe. If someone else could help with that? @ikkez  ? 😄

**Comment by ikkez** [comment]
should be fixed now in the latest commit.
