### ISSUE TITLE
Error on empty belongs-to-many relationship

### ISSUE THREAD

**Issue by delkano** [ikkez/f3-cortex#35]
I have a `belongs-to-many` relationship that may, on occasion, be empty. This is in a SQLite database.

This is not a problem on table creation, nor on model saving, everything goes well and I can see an empty array `[]` in the database.

However, when I try to retrieve the relationship, I get an Internal Server Error on line 1645 (array_unique). If the relationship exists (other database lines have one or several ids in this array), then everything goes well.

**Comment by delkano** [comment]
I've solved it by replacing line 1645 of `lib/db/cortex.php` with
`if(!empty($relKeys) {
    $crit = array($relConf[1].' IN ?', array_unique($relKeys));
}`

**Comment by ikkez** [comment]
thanks for investigation! fix commited.
