### ISSUE TITLE
Out of Memory issue with a Customer<->Booking relation

### ISSUE THREAD

**Issue by module0x90** [ikkez/f3-cortex#37]
Hi,

my DB/Model is setup the following way:

`Customer (1) <-- (n) Booking`
(ie, a Customer can have multiple Bookings and a Booking belongs to one Customer only)

whereas \Model\Customer is defined as
```
            'bookings' => array(-
                'has-many' => array('\Model\Booking', 'customer_id')-
            )-
```

and \Model\Booking as
```
            'customer_id' => array(-
                'belongs-to-one' => '\Model\Customer'-
            ),-
```

and my code does 

`
  $customer = new \Model\Customer();
  $customer->load(array('id = ?', $f3->get('PARAMS.id')));
`

which is then displayed in a template just fine. Bookings are passed as "$customer->bookings".
I inserted some debug code and it looks all ok (so only one record is found for a specific id).

The issue is that while it works for Customers with no Bookings, I am running into a OOM for Customers with one or more Bookings. Just for fun I increased the PHP mem to 1GB, still not working.
It's worth noting that I don't access $customer->bookings at all in my code. It seems the $customer->load() is taking ages/using up all the memory. I have also foreign keys defined in MariaDB and the data are all consistent (no foreign key errors or anything).
The # of DB records are "small": 195 Bookings, 167 Customers, up to 60 Bookings per customer (that's the dev DB with lots of test records).

The error I am getting is

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1249280 bytes) in vendor/bcosca/fatfree-core/db/sql.php on line 189

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1245184 bytes) in vendor/bcosca/fatfree-core/log.php on line 43

Fatal error: Uncaught Whoops\Exception\ErrorException: Unknown: Cannot call session save handler in a recursive manner in Unknown:0 Stack trace: #0 [internal function]: Whoops\Run->handleError(2, 'Unknown: Cannot...', 'Unknown', 0, NULL) #1 {main} thrown in Unknown on line 0

```
What am I missing?

Cheers

Thomas

**Comment by module0x90** [comment]
Erm, sorry.

I found the problem with this.
I had some onload event defined... this was working with FatFree DB tho.

Please close.

**Comment by ikkez** [comment]
alright
