### ISSUE TITLE
Model var savecsd means

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#38]
Hello Christian,

What supposed means to be var $savecsd in model?
What is best practice to configure this?
$savecsd=true or $savecsd['nameField']?
It is auto saved when we inisiate at beginning?

Regards,
Roy

**Comment by ikkez** [comment]
This is just an internal register to store save cascade references. This is not configurable, but used to ensure that everything is saved upon `save()` correctly, so don't touch 😉
