### ISSUE TITLE
Q: How to mark some operartion as "please don't cache"?

### ISSUE THREAD

**Issue by onlyongunz** [ikkez/f3-cortex#39]
I found up that some of my operation, such as saving some same data causing some buggy on the database, so i need to delete all the temps to refresh all the query back again.

Example.
i've saved this:

| id | subject | grand_total | sub_total | tax_total |
|---|-----------|-----------------|---------------|------------|
| 0 | 1  | 0 | 150 | 0 | 

Then i tried to change the `grand_total` and `tax_total`, then i do so. Then this what happened on the database. (after some queries before, and I did call the `save()` method after the updates).

| id | subject | grand_total | sub_total | tax_total |
|---|-----------|-----------------|---------------|------------|
| 0 | 1 | 0 | 150 | 0 |

it didn't even change anything. So i cleaned the temp folder then i retry it again.

Is it my logic error, or is it has a special feature to disable, just for this query?

Thank you.

**Comment by ikkez** [comment]
Sorry, can you clearify the problem please? Is the problem that the update was not saved, or did you just fetched the cached data after successfully updating it? When you've enabled the Cache and provide a `$ttl` to load/find, the underlying mapper will server the same result until `$ttl` expires.

**Comment by onlyongunz** [comment]
It's an empty one, then i added a data, then saved it. (i want to get an id here, so i saved it then use the id)

and then modifies some data, then update it.

the updating proccess are using the "cached query", so the data are not really got updated.

**Comment by ikkez** [comment]
The update query is never using a cache, it must be something else. I could not reproduce the issue yet, and as you usually need to set a $ttl value somewhere, because the query cache is not enabled by default (only the table schema is cached), it's perhabs another load in the controller or something? =) 
Something like this is working just fine:
```php
$f3->set('CACHE', true);
$mapper = new \DB\Cortex($f3->DB,'test_5');
$mapper->subject = 1;
$mapper->grand_total = 0;
$mapper->sub_total = 150;
$mapper->tax_total = 0;
$mapper->save();
$mapper->grand_total = 180;
$mapper->tax_total = 30;
$mapper->save();
print_r($mapper->cast());
print_r($f3->DB->log());
```
```
Array
(
    [id] => 3
    [subject] => 1
    [grand_total] => 180
    [sub_total] => 150
    [tax_total] => 30
)
(0.2ms) [CACHED] SHOW columns FROM `fatfree`.`test_5`
(0.1ms) INSERT INTO `test_5` (`subject`,`grand_total`,`sub_total`,`tax_total`) VALUES (1,0,150,0)
(0.1ms) SELECT `id`,`subject`,`grand_total`,`sub_total`,`tax_total` FROM `test_5` WHERE id=5
(0.1ms) UPDATE `test_5` SET `grand_total`=180,`tax_total`=30 WHERE `id`=5
```

When you do a `$mapper->load(null,null, 300)`, it's using a cached version for 5min, no matter if it was updated in the meanwhile. If you want a fresh copy, don't set a `$ttl` or manually clear the appropriate cache entries. this is something the underlying f3 mapper usually care about 🤔

**Comment by onlyongunz** [comment]
Umm, can you tell me  more about the`$ttl` thing? Because it's not really got updated here, idk why...

this is my code:

```php
    function create_invoice($item, $expire_duration="+3 day", $berita_acara=null, $options=[]){
        //with those items, let's add more
        $this->copyfrom([
            'date_invoice'=>time(),
            'date_due'=> strtotime($expire_duration),
            'status'=>'tertagih',
            'sub_total'=>0,
            'tax_total'=>0,
            'berita_acara'=>$berita_acara
        ]);
        $this->save();
        $items = array_map(function($data){
            var_dump($data);
            $tot = $this->add_item($data);
            $this->sub_total+=$tot->item_total;
            echo (PHP_EOL . $this->sub_total);
            return $tot;
        }, $item);
        
        $this->grand_total = $this->sub_total;
        
        if(isset($options['tax'])){
            $this->tax_total = $this->sub_total * $options['tax'];
        }
        $this->grand_total = $this->sub_total + $this->tax_total;
        $this->copyfrom([
            'subject'=>\F3::get('USER')->_id
        ]); 
        $this->save();
    }
```

**Comment by ikkez** [comment]
Tested that piece and seems to work fine here. If you have a caching issue, it is probably not related to this update method. Check your code where to load the data and think it's still cached. You can also have a look at the database log (`$db->log()`) to see what has be send as update or insert query.

**Comment by onlyongunz** [comment]
aw... okay then, if the problem persist again, i'll reopen this.

Thankyou then... i'll try to patch the code to the production server.
