### ISSUE TITLE
Cortex 1.4.2 ['deleted_at =?', null] problems

### ISSUE THREAD

**Issue by Deprime** [ikkez/f3-cortex#40]
Hello Christian! 
It seems that comparison with NULL is not working or I'm doing something wrong (oftenly - the second option T_T).

I have **category** table with **deleted_at** filed which is **NULL** by default.

Usually I used this method to find not deleted categories:
`$categories = $category->find(['deleted_at IS NULL']);`

But in cortex 1.4.2 this method causes an error. I read the change log and find some new feature like:
- new:  support for NULL filter bind values (like `array('foo != ?',null)`)

So I tried to do like this:
`$categories = $category->find(['deleted_at =?', null]);`

But the query result was empty.
What am I doing wrong? I do not correctly use the new filter?

**Comment by ikkez** [comment]
You're right. I broke this with another commit at a later time. Just fixed and optimized this now in [v1.4.3](https://github.com/ikkez/f3-cortex/releases/tag/v1.4.3) hotfix. Thanks for reporting.

**Comment by Deprime** [comment]
Hello Christian!
There's still some troubles:
`$f3->set('categories', $category->find([' pid=? AND deleted_at=? ',NULL,NULL]));`

and I get the following error message:
`PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULLAND`deleted_at` IS NULL' at line 1`

**Comment by ikkez** [comment]
fixed in the latest commit
