### ISSUE TITLE
Fat-free error Cortex

### ISSUE THREAD

**Issue by crysan** [ikkez/f3-cortex#41]
Hi!

flat-free version 3.6
Code in controller flat-free
```
$db = new \DB\SQL('mysql:host=127.0.0.1;port=3306;dbname=dbTest','tatata','lalala');
$tblBooks = new \DB\Cortex($db, 'tblBooks');
$tblBooks->load(array('id = ?', 1));
$data .= $tblBooks->title;
```
result:
```
Internal Server Error

Fatal error: Declaration of DB\Cortex::count($filter = NULL, array $options = NULL, $ttl = 60) must be compatible with DB\Cursor::count($filter = NULL, $ttl = 0)

[D:/YandexDisk/OpenServer/domains/test2/lib/db/cortex.php:29] 
```

Help me pls!

**Comment by ikkez** [comment]
please use the `1.4.3` [version](https://github.com/ikkez/f3-cortex/releases/tag/v1.4.3) or 1.4.x [branch](https://github.com/ikkez/f3-cortex/tree/v1.4.x), or upgrade F3 to the [dev-version](https://github.com/bcosca/fatfree-core), because there were some changes in F3 > 3.6.0, which are already taken into account on the dev-master here.

**Comment by crysan** [comment]
To archive version 1.4.2

**Comment by ikkez** [comment]
The method declaration of 1.4.3 (and 1.4.2) is compatible with F3 v3.6.0 (but not above that) 
ff. https://github.com/ikkez/f3-cortex/blob/v1.4.3/lib/db/cortex.php#L1173

**Comment by crysan** [comment]
Sorry, but I do not understand how to be.
I have the latest version of flat-free.
Your version 1.4.3, which is displayed in the archive as 1.4.2 did not help.

**Comment by crysan** [comment]
Once again, reinstalled version 3.6.0.
Your error persists.
I ask your verification.

**Comment by ikkez** [comment]
I told you already. download this https://github.com/ikkez/f3-cortex/archive/v1.4.3.zip and this https://github.com/bcosca/fatfree-core/releases/tag/v3.6.0 and it should be compatible.

**Comment by crysan** [comment]
Заработало!
Спасибо!
