### ISSUE TITLE
Name of Auto-Generated 3rd Pivot Table in Many-to-Many Relation

### ISSUE THREAD

**Issue by aristadiki** [ikkez/f3-cortex#42]
Hi, 
I just want to ask, what is the pattern of auto-generated 3rd pivot table name?
Example:
In News Model:
'tags' => array(
    'has-many' => array('\Model\Tag','news'),
)
$table = 'tags';
In Tag Model:
'news' => array(
    'has-many' => array('\Model\News','tags'),
)
$table = 'news';
Is it the 3rd pivot table will be 'news_tags' or 'tags_news' or something else? 

I am asking about this because I want to use a 3rd parameter (name of the pivot table)  in the field configuration and I want to use a prefix in the table.

Thanks

**Comment by ikkez** [comment]
The table names and column names are concatenated and separated by `__`, then alphabethically ordered and glued with `_mm_`. So it becomes `news__tags_mm_tags__news`.

Of course you can set a custom pivot table name, with: 
`'has-many' => array('\Model\Tag','news','news_tags'),`.

If you'd like to prepend that with a global prefix, you can either add a constant there, overwrite the setting dynamically in `__construct` or extend the `getMMTableName` method in your derivate model class - your choice. 😉
