### ISSUE TITLE
save multiple rows into table at once using cortex cursor

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#43]
Hi Christian,
How the best practice to save multiple rows records at once using cortex cursor?
$tableDetail=new cortex();
$tableDetail->erase($findme);
foreach($items as $item){
$tableDetail->reset();
$tableDetail->field1=$val1;
$tableDetail->field2=$val2;
}
$tableDetail->save(); how can I save at once after all cursor has been defined?

Regards,
Roy

**Comment by ikkez** [comment]
The cursor only maps to a single record at a time. Save it directly after making the changes (move ->save() into the foreach loop).

**Comment by royhg** [comment]
Ok, tq.
My situation now is I had lost connection timeout when using cursor save each in the loop, but succeed using cursor ->db->exec at once and I have very limited access to modified the php.ini

**Comment by ikkez** [comment]
Then maybe start a transaction around the foreach loop.

**Comment by royhg** [comment]
Hi Christ,
Another think with almost same condition..
foreach($items as $row=>$item) {
$mp1->reset();
$mp1->copyFrom($item);
$mp1->id=$item['id'];
echo $mp1->cast()  <= Why I cannot set id into $mp1->id? I've tried using copyFrom and manual set into $mp1->id but it seems to be protected.. is it true? how can I set properly this id?
$mp1->save();
}

Regards,
Roy

**Comment by ikkez** [comment]
It's probably because you have set a relation to the id field? something like:

```php
table2.fieldConf=[
'id'=>['belongs-to-one'=>['mTable1','table2']]
]```
see my other comment https://github.com/ikkez/f3-cortex/issues/32#issuecomment-290939960

**Comment by ikkez** [comment]
any updates or solved?

**Comment by royhg** [comment]
table2.fieldConf=[
'id'=>['belongs-to-one'=>['mTable1','id']] // current actually true results, others result null.
]
