### ISSUE TITLE
add support for sub-queries within IN statement

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#44]
Hi Christian,

I found something interesting that the results has different when we load using models and using db direct
My transaction is like below;
Models;
$exec[0]="id not in (?)";
$exec[1]=["select id from table2"];
foreach($values as $value){
$table1->load($exec);
executeSomething that insert table2;
$table1->save();
$table1->cast();
}
Direct:
foreach($values as $value){
$exec="select id from table1 where id not in (select id from table2)";
$results=$table1->db->exec($exec);
executeSomething that insert table2;
echo $results;
}
the $results on direct transaction is always update than $table1->cast() using models.
Side effect using direct transaction made everything models tools become unused..

Regards,

**Comment by ikkez** [comment]
sorry but I think sub-queries in an IN bind parameter is not a supported feature yet, and I find it hard to understand what you write and what you are trying to solve?!
When you just want to save relations, why not do it this way:

```php
$table1->copyFrom('FOO');
$table1->table2->copyFrom('BAR');
$table1->table2->save();
$table1->save();
```

**Comment by royhg** [comment]
I do have master/detail rel that the detail table can save after has an id from the master table

In this case I had a reflection original table that needs to be converted into current table that makes I need to read original table multiple times to be adjusted with current table.

It interesting me that I have different results when I used cursor and direct exec.

Ok, I'll look into another way to solve this conditions.

**Comment by royhg** [comment]
Example:
oriTable has 5000 records
curTable has 1000 records
Table schema has identically same with a little bit modified data.
The interesting part is when I search records id in oriTable compare with curTable using cursor and direct table was has different results that I can't use model load with the already build hooks function than direct db exec with updated records but using manual hooks before executing the script.😫

**Comment by ikkez** [comment]
Just a quick update: to execute sub-queries within an `IN` statement, you have to include the query directly as function i.e.`IN(sql_expression)` and must not add it as prepared statement - that should do the trick:

```php
$table1->load('id not IN(select id from table2)');
``` 

please reopen if problem persists.
