### ISSUE TITLE
Using fields method with a blacklist array, removes virtual fields

### ISSUE THREAD

**Issue by ruimgoncalves** [ikkez/f3-cortex#48]
Using version 1.5.0-dev

``` php
$model->virtual('greet', function($self){
   return 'Hello ' . $self->username;
});
$model->fields(['password'], TRUE);
$model->paginate();
```

The expected result was to have the greet field present in the result set, but all virtual fields are removed after calling fields method with the second argument set to true.

**Comment by ikkez** [comment]
Should be fixed now.
