### ISSUE TITLE
JIG implementation of LIKE operator is case-sensitive

### ISSUE THREAD

**Issue by intermike** [ikkez/f3-cortex#5]
Greetings.

LIKE operator in filter is not case-sensitive according documentation.

But in JIG mapper it is case-sensitive.

I propose to add preg modifier `i` in function `_likeValueToRegEx`.

Also it doesn't support UTF-8, so `u` modifier would be good too.

```PHP
	protected function _likeValueToRegEx($var)
	{
		$lC = substr($var, -1, 1);
		// %var% -> /var/
		if ($var[0] == '%' && $lC == '%')
			$var = '/'.substr($var, 1, -1).'/iu';
		// var%  -> /^var/
		elseif ($lC == '%')
			$var = '/^'.substr($var, 0, -1).'/iu';
		// %var  -> /var$/
		elseif ($var[0] == '%')
			$var = '/'.substr($var, 1).'$/iu';
		return $var;
	}
```

Thanks.

**Comment by ikkez** [comment]
nice catch. fixed in latest commit.

**Comment by intermike** [comment]
Thanks a lot.

I just checked changes with MongoDB and Jig and it works properly.
