### ISSUE TITLE
New working stable version

### ISSUE THREAD

**Issue by SylwesterZarebski** [ikkez/f3-cortex#50]
Hi, is there a roadmap to release stable version at near future?
Current version is 1.4.3, which has broken NULL values (no spaces aroung NULL) and not working with current stable 3.6.1 fatfree.

PS. I appreciate Your great work with this module, just asking :).

**Comment by ikkez** [comment]
The dev version (latest commit on master branch) currently has all the fixes included. I'm just waiting for F3 v3.6.2 to tag a new release.

**Comment by SylwesterZarebski** [comment]
Thanks a lot, do You know when possibly 3.6.2 could be released and then Your module?

**Comment by ikkez** [comment]
done

**Comment by SylwesterZarebski** [comment]
Thanks a lot, You're great :).
