### ISSUE TITLE
Incompatible Declaration of DB\Cortex::count()?

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#51]
Hi Christian,

When I use composer to require cortex v1.4.3 with fatfree v3.6.2 I had that error telling me that incompatible declaration of your count function..
Is it true?

Regards,
royhg

**Comment by ikkez** [comment]
The dev-master has this fixed already. Let me update the docs and then I'll punch out cortex v1.5

**Comment by ikkez** [comment]
there we go https://github.com/ikkez/f3-cortex/releases/tag/v1.5.0
