### ISSUE TITLE
Mapper can't find SQLite entry filtered by NULL field

### ISSUE THREAD

**Issue by delkano** [ikkez/f3-cortex#53]
You can find a description of this bug here: https://groups.google.com/forum/#!topic/f3-framework/mtTTsImf4IM . Essentially, I couldn't use $entries->find("field IS NULL"). I know the README mentions to use $entries->find(array("field = ?", null)) in this situation, but this doesn't work in SQLite.

My solution was to find the Cortex code that quotes the conditions and add exclusions for IS and NULL. In file lib/db/cortex.php, I changed line 2346 from:
`if (preg_match('/\b(AND|OR|IN|LIKE|NOT)\b/i',$match[2]))`
into
`if (preg_match('/\b(IS|NULL|AND|OR|IN|LIKE|NOT)\b/i',$match[2]))`

**Comment by ikkez** [comment]
Actually the build-in query parser rewrites `$entries->find(array("field = ?", null))` to `field IS NULL` on its own. So using `$entries->find(array("field = ?", null))` should work,... at least it does in my unit tests.

**Comment by delkano** [comment]
Ermmm it does. Sorry. I must have written something wrong on my first attempts. I'll close this.
