### ISSUE TITLE
Found Inconsistencies Results on Second Related table or more

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#57]
Hi Christ,

Would you to retest your last release with multiple table related more than two tables?
I found that the second, third, or fourth related table was empty without data when we load/find..
The first one was loaded with true primary called, but sometimes the second and next true called sometime misssed and sometime empty.

Another case is on the copyTo we should provided deep related arguments when the related table exists on the configs, can we have default all related data is copied to the destination array/hive, and optionally  limited the deep data relation when it needs? cause we can limited the column results later using fields() function.

Or in another way how can we detect the deep related table config to translate in the second argument for the copyTo?

Sincere,

**Comment by ikkez** [comment]
Hi,
I'm not a real christ, it's just my first name... just ikkez or chris is fine.
Regarding `copyto`: well it currently is possible to copy related data, even multiple levels deep, with the `$relDepth` argument, see syntax at [cast](https://github.com/ikkez/f3-cortex#cast).
The `copyfrom` method might need  some adjustments here and that's something that'll definitly get some enhancements.

And regarding your load/find issue, it's hard to understand without any details about your constellation.. which database type used?, what type of relation you suspect to be "wrong", are any has/filter methods or something else involved in your load call?.. and when you say "second, third, or fourth related table" you mean on the same model, or a nested relation?

**Comment by royhg** [comment]
Hi ikkez,
Sorry if I missspell ur nickname..
My issue here is using sql type, and wtihout has/filter at all, 
Still configuring the $fieldConf in model initialize, just loading the flat using afind(["id=?",$id]).
The second, third table I used it still in the same model with nested relation.
I'm still investigating the fault, 

class member extends DB\Cortex {
protected
        $table='member',
        $fieldConf=[
        	'fams'=>['has-many'=>['memberFam','id']],
        	'paths'=>['has-many'=>['memberPath','id']]
        ] ;
}

class memberFam extends DB\Cortex {
protected
        $table='memberFam',
        $fieldConf=[
        	'id'=>['belongs-to-one'=>['member','id']]
        ] ;
}

class memberPath extends DB\Cortex {
protected
        $table='memberPath',
        $fieldConf=[
        	'id'=>['belongs-to-one'=>['member','id']],
        ] ;
}

the fams data is always has valid related..
but the paths data sometime valid sometime not even the actual data is already there..

**Comment by royhg** [comment]
I found the mistake, but I dont know how to correcting..
I created fake data each of detail related table with 5 rows.
I tested show result using default find() f3-core function on master,detail1,detail2 and 
using afind() f3-cortex function on master,detail1,detail2. each of initialisation was new and without fieldConf in detail.
the next I tried to update/increase last row data of detail2 to database directly.
then I tried to show each results of master,detail1,detail2 using f3-core find()&f3-cortex afind(), each of results was valid.
But the results of origin cursor that initialisation using fieldConf in detail2 showed that the results of the last updated data it still not updated or showed like before updated/inserted.
Why? 
it was related with any cache or something save in the memory? basically I had setup my f3-hive cache was false and before to show data I run the f3->clear('CACHE');

**Comment by ikkez** [comment]
The problem is that you have configured the `id` field to be a relation.. even if that makes sense from a database perspective, it's not the way it should be configured for the model... actually your configuration is missing the fields for the foreign keys, because you only have primary keys involved.
I think what you actually mean to setup this this:

```php
class member extends DB\Cortex {
  protected $table='member',
  $fieldConf=[
    'fams'=>['has-many'=>['memberFam','member_id']],
    'paths'=>['has-many'=>['memberPath','member_id']]
  ] ;
}

class memberFam extends DB\Cortex {
  protected $table='memberFam',
  $fieldConf=[
    'member_id'=>['belongs-to-one'=>['member','id']]
  ] ;
}

class memberPath extends DB\Cortex {
  protected $table='memberPath',
  $fieldConf=[
    'member_id'=>['belongs-to-one'=>['member','id']],
  ] ;
}
```

**Comment by royhg** [comment]
Hi Ikkez,
So the second field conf after memberFam "member_id" it should be not primary key?
In this configs, "member_id" is on the  memberFam DB or Model?
Ok .. let me try..

**Comment by royhg** [comment]
Hi Ikkez,
Its been a long way to test.. but it still no luck..
table config:
member->id(PK),f1,f2,f3;
memberFam->id(PK),row(PK),mf-f1,mf-f2,mf-f3;
memberPath->id(PK),row(PK),mp-f1,mp-f2,mp-f4;
memberFam&memberPath Primary Key was compound field which (id&row) which id was exists in member table which the primary key is id.

The first test I used fieldConf to bind each relation as the common condition as above, it has no luck results, if I load the cursor with id=1 the memberPath->id results picked id=2.
The second test I used fieldConf to bind each relation as your advised, but I created new model base on view with duplicating id(PK) value with different name as your noticed, but has the same results, if I load the cursor with id=1 the memberPath->id results picked id=2.
The third test I used another way, I released all fieldConf incl slave table and I used virtual field on member which load all records with id=1 on each slave table and the results is the same the memberPath->id picked was id=2 not 1.  

Is it any of my way to call or retrieve slave data was missed or false?
as I remember this issue was never raise in f3-core 3.5.0 with f3-cortex 1.4.0
or did I had something missed or wrong?

Sincere.

**Comment by ikkez** [comment]
It's hard for me to follow your setup.. I made some tests here and this is working fine:

```php
<?php // member.php
class member extends DB\Cortex {
	protected
		$db='DB',
		$table='member',
		$fieldConf=[
			'name' => ['type'=>\DB\SQL\Schema::DT_VARCHAR128],
			'fams'=>['has-many'=>['memberFam','member_id']],
			'paths'=>['has-many'=>['memberPath','member_id']]
		];
}
```

```php
<?php // memberFam.php
class memberFam extends DB\Cortex {
	protected
		$db='DB',
		$table='memberFam',
		$fieldConf=[
			'title' => ['type'=>\DB\SQL\Schema::DT_VARCHAR128],
			'member_id'=>[
				'belongs-to-one'=>'member',
				'index'=>true
			]
		];
}
```
```php
<?php // memberPath.php
class memberPath extends DB\Cortex {
	protected
		$db='DB',
		$table='memberPath',
		$fieldConf=[
			'label' => ['type'=>\DB\SQL\Schema::DT_VARCHAR128],
			'member_id'=>[
				'belongs-to-one'=>'member',
				'index'=>true
			],
		];
}
```
```php
// index.php
$f3->route('GET /cxtest7-test',function( Base $f3, $params) {
	$f3->concat('AUTOLOAD',',cxtest7/');

	$f3->set('DB', new \DB\SQL('mysql:host=localhost;port=3306;dbname=fatfree', 'fatfree', ''));

	member::setup();
	memberFam::setup();
	memberPath::setup();

	$m = new member();
	$m->name = 'John';
	$m->save();

	$fam = $m->rel('fams');
	$fam->title = 'Doe';
	$fam->member_id = $m;
	$fam->save();

	$path = $m->rel('paths');
	$path->label = 'one';
	$path->member_id = $m;
	$path->save();

	$m->reset();
	$m->load();

	print_r($m->cast());
});
```

result 
```
Array
(
    [name] => John
    [fams] => Array
        (
            [0] => Array
                (
                    [title] => Doe
                    [member_id] => 1
                    [_id] => 1
                )

        )

    [paths] => Array
        (
            [0] => Array
                (
                    [label] => one
                    [member_id] => 1
                    [_id] => 1
                )

        )

    [_id] => 1
)
```

database:
![screenshot 2017-11-10 14 37 07](https://user-images.githubusercontent.com/1177647/32663246-912d0dca-c62d-11e7-935f-7cb1cad460a8.png)

**Comment by royhg** [comment]
Hi Ikkez, thank for your reply, hopes my config has as ur conf..
But it little bit a different..
the memberFam and memberPath primary key was the compound fields using id&row, the id in the memberFam/memberPath was reference from member->id, the difference unique key was from row.
I'm not sure my setup on db was in common in normalization method in RDBMS or not. 
But from googling it was enabled to build normalization from compounding fields as a primary key.
But I already used it a lot in another project with another framework.

![db-config](https://user-images.githubusercontent.com/18565328/32680212-38ddf552-c69c-11e7-9c8f-f4fca0cf98fa.png)

**Comment by royhg** [comment]
Hi Ikkez,
It was very sorry.. I found my mistake..
My relation was recursive to make some false return in the results..
Sorry for disturbing the issue..
