### ISSUE TITLE
Optimize has() method for SQL

### ISSUE THREAD

**Issue by SylwesterZarebski** [ikkez/f3-cortex#58]
Hi,
  I propose to enhance current `has()` method for SQL to use EXISTS directive instead of current behaviour.
Example:
```
$items = (new \Model\Item())
  ->has('prices', array('price_currency = ?, $currency))
  ->find('item_status = 1');
```
Currently it works like this:
1. It loads all `prices` elements which gives thousands of rows and takes seconds to load:
```
select price_item from prices where price_currency = ?
```
2. Next it does (which luckily takes shorter amount of time than 1):
```
select * from items where item_status = 1 and item_id in ( ... here is loooong list of item_ids ... )
```
For SQL steps 1 and 2 should be optimized to EXISTS directive:
```
select * from items where item_status = 1 and exists (select price_id from prices where price_item = item_id and price_currency = ?)
```

PS.
In real query there are named fields not *, but for simplicity i wrote *.

PPS.
I've added `price_item = item_id` in where inside exists. Previous version was wrong, sorry.

**Comment by ikkez** [comment]
I agree, this isn't very optimal for larger results. I'll dig into it, I'm not sure yet if `exists` really is the best solution though.

**Comment by SylwesterZarebski** [comment]
Thanks for response. I tested it with MySQL/MariaDB and using exists gives best execution plan - using JOIN was worse.
Of course another SQL enginges could have better execution plans with JOINs.

**Comment by SylwesterZarebski** [comment]
Thanks a lot, could You make release version with this commit?

**Comment by VidhyaApple** [comment]
Is there any method to implement NOT EXISTS directive?

**Comment by ikkez** [comment]
not directly, but you can try to negate the filter you're using within the has-condition. like `foo != ? ` or smth.
