### ISSUE TITLE
JIG: Filter arguments with NULL value disappear

### ISSUE THREAD

**Issue by intermike** [ikkez/f3-cortex#6]
Greetings.

I've caught a bug with filter like
```php
$model->find(array('published_date < ? or published_date = ?', '2015-09-01', null))
```

`_jig_parse_filter` function chops all null values in filter arguments and in result:
```php
array('2015-09-01')
```
so server gives an error.

I don't know would this filter work with SQL, but cutting filter arguments list is not good even there is NULL.

Proposition: remove `if (isset($val))` in `_jig_parse_filter` function where:
```php
if (isset($val))
    $ncond[] = $val;
```
So it will be 
```php
$ncond[] = $val;
```
Thanks.

**Comment by intermike** [comment]
Anyway NULL arguments doesn't work within JIG.

it makes this:
```php
(isset($publish_date) && $publish_date < '2015-09-21') or (isset($publish_date) && $publish_date == NULL)
```
and `isset($publish_date) && $publish_date == NULL` always will be false.

As `null == ''` in PHP so we can changed to:
```php
if (!isset($val)) $val = '';
$ncond[] = $val;
```

**Comment by intermike** [comment]
Sorry, I am wrong.

`isset($publish_date) && $publish_date == ''` will be false too if `publish_date == null`.

Here is solution:
```php
$val = array_shift($args);
$ignore = false;
preg_match('/(@\w+)/i', $part, $match);
// find like operator
if (is_int(strpos($upart = strtoupper($part), ' @LIKE '))) {
	if ($not = is_int($npos = strpos($upart, '@NOT')))
		$pos = $npos;
	$val = $this->_likeValueToRegEx($val);
	$part = ($not ? '!' : '').'preg_match(?,'.$match[0].')';
} // find IN operator
else if (is_int($pos = strpos($upart, ' @IN '))) {
	if ($not = is_int($npos = strpos($upart, '@NOT')))
		$pos = $npos;
	$part = ($not ? '!' : '').'in_array('.substr($part, 0, $pos).
		',array(\''.implode('\',\'', $val).'\'))';
	$ignore = true;
}
// add existence check
if (isset($val)) {
	$part = '(isset(' . $match[0] . ') && ' . $part . ')';
	if (!$ignore)
		$ncond[] = $val;
} else
	$part = 'empty(' . $match[0] . ')';
```
using `$ignore` instead of `unset` of `$val`

**Comment by intermike** [comment]
Some improvement:
```php
$part = (strpos($upart, '==') !== false ? 'isset' : 'empty').'(' . $match[0] . ')';
```
If `publish_date = ?` - it will use `empty` function so: 0, empty string, false, null will work
If `publish_date == ?` - only null.

But this won't probably work exactly same way as SQL.

**Comment by ikkez** [comment]
hey mike. what about a simple switch to `array_key_exists` instead of `isset`? wouldn't that fit too?

**Comment by intermike** [comment]
I thought about that.

But it may need deeply changes. `_jig_parse_filter` return filter with @ started variables. I don't know how would it behaviour if it will be `array_key_exists('publish_date', $_row) && @publish_date == ?`.

Also current solution helps in cases where old records in JIG db have no requested field, due to its recently adding.

As other option, it could be realized as `publish_date` or `!publish_date` or `not publish_date`, just by adding additional check - but that doesn't solve subject (null disappearing).

**Comment by ikkez** [comment]
the latest commit should fix this.
