### ISSUE TITLE
"Cannot use a "has"-filter on non-bidirectional relation field" when using has filter method

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#61]
Hi @ikkez,
I just used the has filter method and had an error below:
"Cannot use a "has"-filter on non-bidirectional relation field".
What is this error means? 
I had already linked master slave column on id at db and had setup too on the fieldConfigs but I had no idea with that message..
Would you enlightened me?
Regards,

**Comment by ikkez** [comment]
Hi. That means that you try to use the `has`-filter on a field that is actually not configured as relation in the `$fieldConf` array or is not the type of `has-one`, `has-many` or `belongs-to-one`.

**Comment by royhg** [comment]
Is it cover up master-detail relation link?
My relation was:
member.id->memberPath.id (database)
member.paths(vf)->memberPath.id (cortex)
memberPath was detail of member which represents in paths virtual field at member model.

**Comment by ikkez** [comment]
And what's your `has`-filter usage then? `$member->has('paths',['foo = ?', 'bar']);`?

**Comment by royhg** [comment]
$member->has('paths,["pathId=?",2]);
I want to filter all member with has paths with pathId=2 
And then the error showed up.

**Comment by ikkez** [comment]
Hey roy. You still got the issue? If so please provide some basic config for your member.paths setup? It's a `has-one` type connection I think?

**Comment by ikkez** [comment]
configuration issue, no relations on `id` allowed.. add a proper foreign key, no other workarounds planned to be included so far.
