### ISSUE TITLE
The fields() method seconds params to blacklisted

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#63]
Hi @ikkez,
Want to make sure the purpose of used second params of fields() when set it true is to blacklisted show of the first params key array? It means that the other fields name is show enable or blacklisted too?

In my case now is blacklisted..is it true?

Regards

**Comment by ikkez** [comment]
The fields in the 1st param are not shown anymore, when you have the 2nd `$exclude` parameter set to `true`. There are some samples right here: https://github.com/ikkez/f3-cortex#fields

**Comment by royhg** [comment]
Dear @ikkez,
The other fields NOT listed on the first params is blacklisted/not shown too?
Sorry in my case is not shown or blacklisted too.. is it true?
Regards,

**Comment by ikkez** [comment]
it depends on whether `$exclude` is true or not.. if yes, all other fields are shown, if not, then only the fields given are shown.

**Comment by royhg** [comment]
Hi @ikkez,
Yes I think I dont missundestand here, 
fields=[field1,field2,field3,field4,field5];
It should when I define $mapper->fields([field4],true), 
the other fields like field1,field2,field3&field5 should be shown?
In my case I tested the other fields is not shown, let me rechecked again if is it true or not.
Cause before I asked you I already checked many times.
Regards,

**Comment by royhg** [comment]
Hi @ikkez,
Shame on me...
I tried in another apps your fields() is true! oooh very sorry that makes you busy..
Regards,
