### ISSUE TITLE
Checking with isset() when NULL returns TRUE

### ISSUE THREAD

**Issue by ursulnegrul** [ikkez/f3-cortex#72]
#Reproduce
`$DB = new \DB\Cortex(new \DB\SQL('sqlite:database.sq3'), 'mytable');`
`$DB->varA = null;`

#Rezult
`isset($DB->varA) === true`

#Expected
`isset($DB->varA) === false`

**Comment by ikkez** [comment]
please check if https://github.com/bcosca/fatfree-core/commit/e0bcd7fc1f07355574df3ceee7f3100dbee9222f solves your issue.
