### ISSUE TITLE
Paginating has-many relationship

### ISSUE THREAD

**Issue by delkano** [ikkez/f3-cortex#73]
I'm trying to avoid memory issues and would like to paginate relationships.
Essentially, I have categories and items in those categories. When I load an extremely large category (containing > 8000 items), I can't access its "items" relationship without getting a "memory exhausted" exception.

What I'd like is to paginate the relationship, but I can't find an easy way to do it. What would be the best way to achieve this?

**Comment by ikkez** [comment]
Hi. You could paginate relations by adding a `$category->filter('items',null,['limit'=>10,'offset'=>0])` but I you can also just use the items as aggregation point and load the items by the item model itself which are from that category.. depending on your table schema, it could be a benefit.
