### ISSUE TITLE
Deleting has-many <-> has-many

### ISSUE THREAD

**Issue by delkano** [ikkez/f3-cortex#76]
I have two models with a mutual has-many relationship. Let's conceptualize it as:
    user(id, name, bookmarks)
    books(id, title, bookmarkers)

Everything works perfectly alright but for one thing.
Let's say I do:

    user->bookmarks = [ 1, 2];
    user->save();

This is good, my intermediary table gets filled with the relationships, all good. But then, later:

    user->bookmarks = [];
    user->save();

Not so good: relationships are not deleted, so on subsequent calls we still get `user->bookmarks == [1, 2]` (well, not 1,2, but the full mappers).

What would be the best way to update this kind of relationships?

**Comment by delkano** [comment]
OK, I've found it works if I set the bookmarks to null, but not to an empty array.

I'll leave the issue open because it's still a bug, but my personal issue is solved.

**Comment by ikkez** [comment]
Hi there. I've made a little fix, though not fully tested yet, it should fix it.. perhaps you can give it a try.

**Comment by cryogenx** [comment]
along these same line what if I only want to remove one of the relations? 

e.g.

role...............has-many....permissions
permission...has-many....roles

role1->permissions[1,2,3]
role2->permissions[1,3,4]

in need to remove permission [3] from role1
so all done it should be:

role1->permissions[1,2]
role2->permissions[1,3,4]

does that make sense?

**Comment by delkano** [comment]
Thanks, ikkez, that should do it.

cryogenx, I'm not sure what you mean. If I understand you correctly, you want to be able to do: `role1->permissions = [1,2]` and thus remove 3? It's already like this.
