### ISSUE TITLE
Problems adding IDs to belongs-to-many/unidirectional

### ISSUE THREAD

**Issue by eazyliving** [ikkez/f3-cortex#8]
Hi,

I have two Models using belongs-to-many. They look like this:

```
class feedURL extends \DB\Cortex  {
		protected $fieldConf = array(
		...
		'touser' => array(
					'belongs-to-many' => '\Model\user'
				),
				
		);
		...
}
```

I can assign IDs to 'touser' with 

```
$feedURL->touser = array (1,2)
```

but adding IDs with 

```
$feedURL->touser[]= 1; 
$feedURL->touser[]=$mappeduser;
```
does not work.

To keep things short: I think, adding IDs to belongs-to-many with [] doesn't work.

Hope, you can reproduce that!

[update]
Sorry, has-many doesn't take [] either :(
[/update]

**Comment by ikkez** [comment]
Hi.
Well for has-many fields, I know that this only works for existing relations, so this works:
```php
if ($feedURL->touser) {
  $feedURL->touser[] = 1
} else {
  $feedURL->touser = array(1);
}
```

Maybe you can have a try like this for belongs-to-many fields too.

**Comment by eazyliving** [comment]
Hi Christian,

sorry, that doesn't work (for me). Neither for has-many nor for belongs-to-many. Am I holding it wrong? :)

I now test for the relation to exist, but it only adds the first relation. Any additional relation added with [] does not appear in the pivot table (hasmany) or the field (belongstomany).

I have no idea where to start...

**Comment by ikkez** [comment]
Hey Christian, I tested all once more just to be sure. For m:m relations (has-many <> has-many) it did work the way described above. One importent thing is that you really need to save each of both models before, otherwise it cannot find the correct record id, cause it isn't existing yet (well, maybe I can improve that later). Nevertheless I've found an issue for belongs-to-many fields, which should follow the same syntax. I've added a fix https://github.com/ikkez/f3-cortex/commit/12f5eccc43648d3e83a7cd68990a1912cd079b64. This should work now for both m:m types:
```php

$tag = new TagModel();
$tag->title='testtag';
$tag->save();

$news = new NewsModel();
$news->title = "new test 1";
$news->text = "super duper cool";
$news->save();

if($news->tags) {
	$news->tags[] = $tag;
} else {
	$news->tags = array($tag);
}
$news->save();
```

**Comment by eazyliving** [comment]
Hi Christian :)

Thanks a lot, but this is not the end :]

To be sure that it's not my installation or app that breaks things, I took your testsuite for cortex and build a fresh f3 with that and the latest patch of cortex.

Turns out: Your testcode from above works. Great! :) But it only works while using the mapper objects. Using IDs like this:
```
$news1->tags = array($tag1->id,$tag2->id);
$news1->tags[] = $tag2->id;
$news1->save();
```
results in this error:

```
Fatal error: Call to a member function exists() on a non-object
[hosted/cortex/lib/db/cortex.php:2527]
```
I can initialize tags any way I want. Mappers, IDs: doesn't matter. But adding IDs with [] doesn't work .

Am I still holding it wrong? :)

**Comment by ikkez** [comment]
hehe. nope you're not holding it wrong. Just finding some sharp edges on the latest added features ;)
Latest commit should fix this ;) thanks for reporting.

**Comment by eazyliving** [comment]
Great! Works! Thanks a lot.
Cortex is a great thing. I love f3 and build some projects around that. A podcast publisher (firtz.org) and the flattrboard (flattrboard.hoersuppe.de). 

But these projects lag a solid fundament in terms of classes and models. Cortex "forces" me to think about what I need before building the app. That's a painful process sometimes (getting your relations together...), but afterwards I get rewarded with a sleeky to use system. Thanks!

**Comment by ikkez** [comment]
hehe. yeah maybe I'll build a little drag&drop model creator when i find some time during holidays. that would probably be handy :)
nevertheless, great to see all those f3 projects growing up. happy coding!
