### ISSUE TITLE
has() OR has()

### ISSUE THREAD

**Issue by delkano** [ikkez/f3-cortex#82]
Is there any way to do a list of "OR" connected has() conditions?

For example, let's assume I have a `User` model with two has-many reciprocal relationships, `followers` and `follows`. 

Let's say I want to all users within a user's circle (comprising all followers and followed people) which have a certain name (for example).

I would like to do:

    $users->has("follows", ["id=?", $me->id]);
    $users->orHas("followers", ["id=?", $me->id]);
    $users->find(["name=?", $name]);

(or something similar).

Is there any way to something like this without doing two separate queries?

**Comment by ikkez** [comment]
No not really, but you can change the aggreation point to make it a little easier to query, i.e.:

```php
$me->filter("follows", ["name=?", $name]);
$me->filter("followers", ["name=?", $name]);
$me->load(["id=?", $myId]);
$users = array_merge($me->follows?:[], $me->followers?:[]);
```

The results are not unique though.... so it's not that handy at the moment, sry.

**Comment by ikkez** [comment]
There's an `orHas()` method now.
