### ISSUE TITLE
Align return type of `find()` between cortex and f3?

### ISSUE THREAD

**Issue by kumy** [ikkez/f3-cortex#87]
While using `paginate()` from f3, I've found that when coupled with cortex and the `filter` returns no results, then the `paginate.subset` has a value of `false` (In my case it causes me troubles in smarty templates where `foreach` executes a loop when value is `false` :/)

I've not tested on pure f3, but looking at the source code and documentation, we should obtain in this case an empty array. So wouldn't be preferable to align those cases and always return an empty `CortexCollection` on cortex side?

BTW, there are some inconsistencies, documentation (readme) and function itself say it returns `CortexCollection|false`, but the function docstring says `CortexCollection` (no bool). I think only the docstring is correct.
https://github.com/ikkez/f3-cortex/blob/5521ebc474ac8a9a34e46d72f180bfb4d4b00c3a/lib/db/cortex.php#L593-L600

@ikkez what's your opinion?

**Comment by ikkez** [comment]
I had this on my desk quite a while ago and the one or other solution did have some side effects that where more annoying than simply checking against the boolean value in your template before `foreach`'ing through it.. a little and easy fix though: `foreach($mapper->foo?:[] as $item)`  which just passes an empty array if the relation is false.
Returning an empty array can be a bummer when you think it's a collection, and add items to it, like `$mapper->foo[] = $bar`, but actually it wont save this relations..
returning an empty CortexCollection will strike through tests against bool or empty in your templates and controllers and can lead to unexpected behaviours.. sadly.
So the best deal I came up with was to simple return FALSE in case nothing was found. Easy enough to handle I guess, but I'm open for other ideas, as long as working with it remains natural and easy to understand. by the way thanks for digging into the code and docs and your commits. +1

**Comment by kumy** [comment]
Let's at least fix the docstring (See PR #89)
