### ISSUE TITLE
rollback a transaction left object in a valid state

### ISSUE THREAD

**Issue by kumy** [ikkez/f3-cortex#90]
When we rollback a transaction, the previously saved objects stay in a valid state (valid per use of `dry()`/`valid()` functions).

I would have expected the `dry()` function to return `true`.

here is a little example:
```php
$f3->get('DB')->begin();
$move = new Move();
$move->comment = 'Some comment';

var_dump(move->dry());
$move->save();
var_dump(move->dry());

$f3->get('DB')->rollback();
var_dump(move->dry());
```

This outputs:
```
bool(true)
bool(false)
bool(false)
```

But I expect it to return:
```
bool(true)
bool(false)
bool(true)
```

**Comment by ikkez** [comment]
Well the mappers don't know when a transaction has started or rolled back and also if, it would be difficult to know to what state to return. If that's a feature request, it would rather go to fatfree-core instead.. but I also have no idea yet how an implementation could look like 🤔

**Comment by kumy** [comment]
Do you have a way to move the issue there, or should I create it from scratch?

**Comment by ikkez** [comment]
I cannot move the issue.
