### ISSUE TITLE
Need help running cortex

### ISSUE THREAD

**Issue by NetLancer** [ikkez/f3-cortex#91]
Sorry guys, tried out for several hours now & can't guess where the clue is (doesn't work):
<?php
namespace Model;
$f3 = \Base::instance();
$f3->set('DB', $f3->get('DB2->connect'));  // DB2 class with connect method
  // work ok in other places

class Carrier extends \DB\Cortex {
  protected
  $db = 'DB',
  $table = 'carriers', // existing table 
  $tbl = new \Model\Carriers();

    function __construct() { // tried $this->tbl assigning in here too }

public function all() {
  $r = $this->tbl->find();
  foreach($r as $one) echo $one['carrier_name'] ."\n";

// outputs - all kind of errors..
}
// crying out for help

**Comment by ikkez** [comment]
you need to set `$this->tbl` within contruct, that correct, but you're missing the call to parent::__construct() ;)

**Comment by NetLancer** [comment]
`namespace Model;

class Carrier extends \DB\Cortex {
  protected
  $db,
  $table = 'carriers', // existing table
  $tbl;

    public function __construct($f3) {
       $this->db = $f3->call('DB2->connect');
       $this->tbl = new \Model\Carriers();
       parent::__construct();
//        $this->tbl = new \Model\Carriers(); ..tried both - before/after parent::__construct 
   }

public function all() {
  $r = $this->tbl->find();
  foreach($r as $one) echo $one['c_name'];
}`

Totally confused, still doesn't want to run. What am i missing ???

**Comment by NetLancer** [comment]
On the other hand, what limitations has the simple configuration thing like:
"$tbl = new \DB\Cortex($db, 'users')" as compared with advanced one?
I mean presently my concern is smooth json-encoded data output for js library to parse
