### ISSUE TITLE
An SQL table is not dropped by setdown() if its name is mixed case

### ISSUE THREAD

**Issue by miseeger** [ikkez/f3-cortex#93]
I've encountered a problem when setting down an existing table which name is mixed case. The ["strtolower" in function setdown()](https://github.com/ikkez/f3-cortex/blob/d83c7dc4a47a763f4cc3820e1e5516e7fa446b26/lib/db/cortex.php#L427) prevents a table to be dropped which name in my case is/was "elvs_Event". When calling the setdown() method on my model class without any params it's never found in the list of db-tables [when checked before dropping](https://github.com/ikkez/f3-cortex/blob/d83c7dc4a47a763f4cc3820e1e5516e7fa446b26/lib/db/cortex.php#L464) because "elvs_event" is checked against "elvs_Event" (the more correct tablename). A simple remove of the mentioned "strtolower()" solved my problem.

**Comment by ikkez** [comment]
fixed. thx
