### ISSUE TITLE
Translation tables

### ISSUE THREAD

**Issue by delkano** [ikkez/f3-cortex#94]
I am trying to build a translatable API.
My ideal database architecture would be something akin to:
`sometable (id, variousdata1, variousdata2, ...)`
`sometable_i18n (id, sometable, langcode, translateddata1, translateddata2, ...)`.

With such structure, I could for example find sometable id.1 with strings in languaage 'en' with a simple LEFT JOIN:
`SELECT * FROM sometable LEFT JOIN sometable_i18n ON sometable_i18n.sometable = sometable.id AND langcode='en' WHERE id=1`

However, I am having some trouble seeing how to implement something like this in Cortex. Has any one some idea about how to do it, or any kind of alternative way?

**Comment by ikkez** [comment]
This looks like a simple has relation to me. I.e. if there are multiple i18n entries regarding sometable.id=1, it's a has-many <> belongs-to-one

**sometable** with $fieldconf: 
`'i18n' => ['has-many'=>['Sometable_i18nModel','sometable']]
and **Sometable_i18nModel** with
`'sometable' => ['belongs-to-one'=>['SomeTableModel','id']]

to do the query:

```php
$sometable = new Sometable();
$sometable->has('i18n', ['langcode = ?', 'en']);
$sometable->load(['id = ?', 1]);
foreach($sometable->i18n ?: [] as $i18n)
  echo $i18n->translateddata1;
```

`

**Comment by delkano** [comment]
I was definitively overthinking this. Thank you.
